#å¦‚æœä¸çŸ¥é“è‡ªå·±åœ¨å¹²ä»€ä¹ˆè¯·åˆ«åŠ¨ç€ä¸¤è¡Œ
ip: 127.0.0.1
port: 5555

admins: ['']

command_prefix: "/"

menu_key: ["èœå•", "help", "cd"]
main_menu: "-----XYBotèœå•------\nå®ç”¨åŠŸèƒ½âš™ï¸\n1.1 è·å–å¤©æ°”\n1.2 è·å–æ–°é—»\n1.3 ChatGPT\n\nå¨±ä¹åŠŸèƒ½ğŸ”¥\n2.1 éšæœºå›¾å›¾\n\nç§¯åˆ†åŠŸèƒ½ğŸ’°\n3.1 ç­¾åˆ°\n3.2 æŸ¥è¯¢ç§¯åˆ†\n3.3 ç§¯åˆ†æ¦œ\n\nå¸®åŠ©æŒ‡ä»¤æ ¼å¼/èœå• (ç¼–å·)\nä¾‹å¦‚/èœå• 1.1\næŒ‡ä»¤å‚æ•°çš„()ä¸ç”¨æ‰“"

menus: {"1.1": "-----XYBotèœå•------\n1.1: è·å–æœ€æ–°å®æ—¶å¤©æ°”ğŸŒ§ï¸\næŒ‡ä»¤ï¼š/è·å–å¤©æ°” (åŸå¸‚)\nâš ï¸æ³¨æ„åªæ”¯æŒå›½å†…åŸå¸‚",
        "1.2": "-----XYBotèœå•------\n1.2: è·å–æœ€æ–°å¤´æ¡æ–°é—»ğŸ“°\næŒ‡ä»¤: /æ–°é—»",
        "1.3": "-----XYBotèœå•------\n1.3: åœ¨å¾®ä¿¡ä¸­ç”¨ChatGPTğŸ¤–ï¸\n(æ”¯æŒç§èŠ)\næŒ‡ä»¤ï¼š/gpt (é—®é¢˜)\nâš ï¸æ³¨æ„ï¼æ‰£é™¤3ç‚¹ç§¯åˆ†ï¼âš ï¸",
        "2.1": "-----XYBotèœå•------\n2.1: éšæœºä¸€ä¸ªäºŒæ¬¡å…ƒå›¾ç‰‡ï¼\næŒ‡ä»¤ï¼š/éšæœºå›¾å›¾",
        "3.1": "-----XYBotèœå•------\n3.1: ç­¾åˆ°é¢†å–ç§¯åˆ†\nâš ï¸æ¯å¤©åªèƒ½é¢†å–ä¸€æ¬¡(æ¯å¤©3ç‚¹åˆ·æ–°)\næŒ‡ä»¤ï¼š/ç­¾åˆ°",
        "3.2": "-----XYBotèœå•------\n3.2: æŸ¥è¯¢è‡ªå·±çš„ç§¯åˆ†ï¼\næŒ‡ä»¤ï¼š/æŸ¥è¯¢ç§¯åˆ†",
        "3.3": "-----XYBotèœå•------\n3.3: æŸ¥çœ‹ç§¯åˆ†æ’è¡Œæ¦œï¼\næŒ‡ä»¤ï¼š/ç§¯åˆ†æ¦œ"}

random_pic_key: ["éšæœºå›¾å›¾"]
random_pic_url: "https://dev.iw233.cn/wbapi.php?sort=random"

# å•†ä¸šè½¬è½½è¯·è”ç³»ä½œè€…è·å¾—æˆæƒï¼Œéå•†ä¸šè½¬è½½è¯·æ³¨æ˜å‡ºå¤„ã€‚
# For commercial use, please contact the author for authorization. For non-commercial use, please indicate the source.
# åè®®(License)ï¼šç½²å-éå•†ä¸šæ€§ä½¿ç”¨-ç›¸åŒæ–¹å¼å…±äº« 4.0 å›½é™… (CC BY-NC-SA 4.0)
# ä½œè€…(Author)ï¼š730716745
# é“¾æ¥(URL)ï¼šhttps://blog.anosu.top/archives/22
# æ¥æº(Source)ï¼šAnosu
random_pic_link_key: ["éšæœºé“¾æ¥"]
#è®¾ç½®æ•°é‡ï¼Ÿçœ‹åˆ°é“¾æ¥æœ€åé¢é‚£ä¸ªæ•°å­—æ²¡ï¼Ÿæ”¹å®ƒï¼
random_pic_link_url: "https://moe.jitsu.top/img/?type=json&num=3"

signin_key: ["ç­¾åˆ°"]
query_points_key: ["æŸ¥è¯¢ç§¯åˆ†", "ç§¯åˆ†æŸ¥è¯¢"]
points_leaderboard_key: ["ç§¯åˆ†æ¦œ", "ç§¯åˆ†æ’è¡Œæ¦œ"]

#ChatGPTçš„APIç½‘å€
openai_api_base: ""
#ChatGPT APIçš„Key
openai_api_key: ""
gpt_key: ["gpt", "chatgpt", "GPT", "ChatGPT", "CHATGPT"]
gpt_version: 'gpt-3.5-turbo'
gpt_point_price: 3

#è¯·å» https://www.yiketianqi.com/ ç”³è¯·APIå¯†é’¥
weather_key: ["å¤©æ°”", "è·å–å¤©æ°”"]
weather_api: "https://v0.yiketianqi.com/free/day"
weather_appid: ""
weather_appsecret: ""

#å¯æ›´æ”¹ å‚è€ƒï¼šhttps://blog.csdn.net/qq_41212530/article/details/85693158
news_key: ["æ–°é—»", "news", "new", "è·å–æ–°é—»"]
news_urls: ["http://c.m.163.com/nc/article/headline/T1348647853363/0-20.html", "https://c.m.163.com/nc/article/headline/T1348649580692/0-20.html", "http://c.3g.163.com/nc/article/list/T1348648517839/0-20.html"]
news_number: 3

admin_whitelist: ["ç®¡ç†ç™½åå•"]
admin_points: ["ç®¡ç†ç§¯åˆ†"]
admin_signin_reset: ["é‡ç½®ç­¾åˆ°çŠ¶æ€", "é‡ç½®ç­¾åˆ°", "é‡ç½®ç­¾åˆ°æ•°æ®åº“"]