version: "3.3"

services:
    xybot:
        image: "henryxiaoyang/xybot:latest"
        restart: unless-stopped
        container_name: "XYBot"
        environment:
            WC_AUTO_RESTART: "yes"
        ports:
            - "4000:8080"
        extra_hosts:
            - "dldir1.qq.com:127.0.0.1"
        volumes:
              - "XYBot:/home/app/XYBot/"
              - "XYBot-wechatfiles:/home/app/WeChat Files/"
        tty: true

volumes:
    XYBot:
    XYBot-wechatfiles: